name: Manual Release

on:
  workflow_dispatch:
    branches:
      - "master"
    inputs:
      bump_type:
        description: "Type of version bump. Choose from: patch, minor, major"
        required: true
        default: "patch"

jobs:
  release:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      - run: yarn build

      - name: Determine version bump
        id: bump_version
        run: echo "::set-output name=bump_type::${{ github.event.inputs.bump_type }}"

      - name: Bump version
        id: version-bump
        uses: anothrNick/github-tag-action@1.61.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ steps.bump_version.outputs.bump_type }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}

      - name: Publish to npm registry
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # In case of failure
      - name: Rollback on failure
        if: failure()
        uses: author/action-rollback@stable
        with:
          release_id: ${{ steps.create_release.outputs.id }}
          tag: ${{ github.ref }}
          delete_orphan_tag: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
